### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by FilipCeynowa** [3DPrintDemon/Demon_Essentials_Voron_2.4_Edition#1]
Hi, 

I get this: 

Error evaluating 'gcode_macro _DEMON_VERSION:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'gcode_macro _SH_VERSION'

**Comment by 3DPrintDemon** [comment]
issue due to naming issue, now resolved.
